<?php global $var_yttheme;  
// Include cpanel
if( $var_yttheme->getParam('showCpanel') ) {
?>
<div id="cpanel_wrapper" style="direction:ltr">
	<div class="cpanel-head">Template Settings</div>
    <div class="cpanel-theme-color">
    	<span class="theme-color-heading">Select color sample for all params</span>
        <div class="inner clearfix">
            <span title="Yellow" 		class="theme-color yellow<?php echo ($var_yttheme->getParam('sitestyle')=='yellow')?' active':'';?>">Yellow</span>
            <span title="Pink" 			class="theme-color pink<?php echo ($var_yttheme->getParam('sitestyle')=='pink')?' active':'';?>">Pink</span>
            <span title="Green" 		class="theme-color green<?php echo ($var_yttheme->getParam('sitestyle')=='green')?' active':'';?>">Green</span>
            <span title="Purple" 		class="theme-color purple<?php echo ($var_yttheme->getParam('sitestyle')=='purple')?' active':'';?>">Purple</span>
            <span title="Cyan" 	class="theme-color cyan<?php echo ($var_yttheme->getParam('sitestyle')=='cyan')?' active':'';?>">Cyan</span>
        </div>
    </div>
    <div class="accordion" id="ytcpanel_accordion">
    	<!--Body-->
        <div class="accordion-group cpnel-body">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#ytcpanel_accordion" href="#ytitem_1">
                Body
                </a>
            </div>
            <div id="ytitem_1" class="accordion-body collapse in">
                <div class="accordion-inner clearfix">
                    <!-- Body Background color -->
                    <div class="cp-item body-background-color">
                        <span>Background color</span>
                        <div class="inner">
                        	<input type="text" value="<?php echo $var_yttheme->getParam('bgcolor');?>" autocomplete="off" size="7" class="color-picker miniColors" name="ytcpanel_bgcolor" maxlength="7"/>
                        </div>
                    </div>
                    <!-- Link color-->
                    <div class="cp-item link-color">
                        <span>Link color</span>
                        <div class="inner">
                        	<input type="text" value="<?php echo $var_yttheme->getParam('linkcolor');?>" autocomplete="off" size="7" class="color-picker miniColors" name="ytcpanel_linkcolor" maxlength="7"/>
                        </div>
                    </div>
                    <!-- Text color-->
                    <div class="cp-item text-color">
                        <span>Text color</span>
                        <div class="inner">
                        	<input type="text" value="<?php echo $var_yttheme->getParam('textcolor'); ?>" autocomplete="off" size="7" class="color-picker miniColors" name="ytcpanel_textcolor" maxlength="7"/>
                        </div>
                    </div>
      				<!-- Background image-->
                    <div class="cp-item body-background-image">
                        <span>Background image</span>
                        <div class="inner">
                        	<input type="hidden" name="ytcpanel_body-bgimage" value="<?php echo $var_yttheme->getParam('body-bgimage'); ?>"/>
                            <a href="#bd" title="pattern1" class="pattern pattern1<?php echo ($var_yttheme->getParam('body-bgimage')=='pattern1')?' active':''?>">pattern1</a>
                            <a href="#bd" title="pattern2" class="pattern pattern2<?php echo ($var_yttheme->getParam('body-bgimage')=='pattern2')?' active':''?>">pattern2</a>
                            <a href="#bd" title="pattern3" class="pattern pattern3<?php echo ($var_yttheme->getParam('body-bgimage')=='pattern3')?' active':''?>">pattern3</a>
                            <a href="#bd" title="pattern4" class="pattern pattern4<?php echo ($var_yttheme->getParam('body-bgimage')=='pattern4')?' active':''?>">pattern4</a>
                            <a href="#bd" title="pattern5" class="pattern pattern5<?php echo ($var_yttheme->getParam('body-bgimage')=='pattern5')?' active':''?>">pattern5</a>
                        </div>
                    </div>					
                </div>
            </div>
        </div>
        <!-- Header-->
		 
        <div class="accordion-group cpanel-header">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#ytcpanel_accordion" href="#ytitem_2">
                Header
                </a>
            </div>
        	<div id="ytitem_2" class="accordion-body collapse">
                <div class="accordion-inner clearfix">
                	<!-- Background color -->
                    <div class="cp-item header-background-color">
                        <span>Background color</span>
                        <div class="inner">
                        	<input type="text" value="<?php echo $var_yttheme->getParam('header-bgcolor');?>" autocomplete="off" size="7" class="color-picker miniColors" name="ytcpanel_header-bgcolor" maxlength="7"/>
                        </div>
                    </div>
      				<!-- Background image-->
                    <div class="cp-item header-background-image">
                        <span>Background image</span>
                        <div class="inner">
                        	<input type="hidden" name="ytcpanel_header-bgimage" value="<?php echo $var_yttheme->getParam('header-bgimage'); ?>"/>
                            <a href="#bg_menu" title="hpattern1" class="pattern hpattern1<?php echo ($var_yttheme->getParam('header-bgimage')=='hpattern1')?' active':''?>">hpattern1</a>
                            <a href="#bg_menu" title="hpattern2" class="pattern hpattern2<?php echo ($var_yttheme->getParam('header-bgimage')=='hpattern2')?' active':''?>">hpattern2</a>
                            <a href="#bg_menu" title="hpattern3" class="pattern hpattern3<?php echo ($var_yttheme->getParam('header-bgimage')=='hpattern3')?' active':''?>">hpattern3</a>
                            <a href="#bg_menu" title="hpattern4" class="pattern hpattern4<?php echo ($var_yttheme->getParam('header-bgimage')=='hpattern4')?' active':''?>">hpattern4</a>
                            <a href="#bg_menu" title="hpattern5" class="pattern hpattern5<?php echo ($var_yttheme->getParam('header-bgimage')=='hpattern5')?' active':''?>">hpattern5</a>
                        </div>
                    </div>
				</div>
			</div>
        </div>
		 
        <!-- Footer-->
        <div class="accordion-group cpanel-footer">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#ytcpanel_accordion" href="#ytitem_3">
                Footer
                </a>
            </div>
            <div id="ytitem_3" class="accordion-body collapse">
                <div class="accordion-inner clearfix">
                	<!-- Background color -->
                    <div class="cp-item footer-background-color">
                        <span>Background color</span>
                        <div class="inner">
                        	<input type="text" value="<?php echo $var_yttheme->getParam('footer-bgcolor');?>" autocomplete="off" size="7" class="color-picker miniColors" name="ytcpanel_footer-bgcolor" maxlength="7"/>
                        </div>
                    </div>
                    <!-- Background image-->
                    <div class="cp-item footer-background-image">
                        <span>Background image</span>
                        <div class="inner">
                        	<input type="hidden" value="<?php echo $var_yttheme->getParam('footer-bgimage');?>" name="ytcpanel_footer-bgimage" />
                            <a href="<?php /* #yt_footerwrap */ ?>#bg_footer_bottom" title="fpattern1" class="pattern fpattern1<?php echo ($var_yttheme->getParam('footer-bgimage')=='fpattern1')?' active':''?>">fpattern1</a>
                            <a href="<?php /* #yt_footerwrap */ ?>#bg_footer_bottom" title="fpattern2" class="pattern fpattern2<?php echo ($var_yttheme->getParam('footer-bgimage')=='fpattern2')?' active':''?>">fpattern2</a>
                            <a href="<?php /* #yt_footerwrap */ ?>#bg_footer_bottom" title="fpattern3" class="pattern fpattern3<?php echo ($var_yttheme->getParam('footer-bgimage')=='fpattern3')?' active':''?>">fpattern3</a>
                            <a href="<?php /* #yt_footerwrap */ ?>#bg_footer_bottom" title="fpattern4" class="pattern fpattern4<?php echo ($var_yttheme->getParam('footer-bgimage')=='fpattern4')?' active':''?>">fpattern4</a>
                            <a href="<?php /* #yt_footerwrap */ ?>#bg_footer_bottom" title="fpattern5" class="pattern fpattern5<?php echo ($var_yttheme->getParam('footer-bgimage')=='fpattern5')?' active':''?>">fpattern5</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Menu -->
        <div class="accordion-group cpanel-footer">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#ytcpanel_accordion" href="#ytitem_6">
                Menu style
                </a>
            </div>
            <div id="ytitem_6" class="accordion-body collapse">
                <div class="accordion-inner clearfix">
                	<!-- Styles -->
                    <div class="cp-item footer-background-color">
                        <span>Styles</span>
                        <div class="inner">
                        	<select onchange="javascript: onCPApply();" name="ytcpanel_menustyle" class="cp_select">
                                <option value="mega"<?php echo ($var_yttheme->getParam('menustyle')=='mega')?' selected="selected"':'';?>>Mega</option>
                                <option value="css"<?php echo ($var_yttheme->getParam('menustyle')=='css')?' selected="selected"':'';?>>Css</option>
                                <option value="split"<?php echo ($var_yttheme->getParam('menustyle')=='split')?' selected="selected"':'';?>>Split</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Typography -->
        <div class="accordion-group cpanel-typography">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#ytcpanel_accordion" href="#ytitem_4">
                Typography
                </a>
            </div>
            <div id="ytitem_4" class="accordion-typo collapse">
                <div class="accordion-inner clearfix">
                	<!-- Google font -->
                    <div class="cp-item">
                        <span>Google font</span>
                        <div class="inner">
                        	<?php 
							$googleFont = array(
										'Archivo Narrow'		=>'Archivo Narrow',
										'Oswald'		=>'Oswald',
										'Open Sans'		=>'Open Sans',
										'BenchNine'		=>'BenchNine',
										'Droid Sans'	=>'Droid Sans',
										'Droid Serif'	=>'Droid Serif',
										'PT Sans'		=>'PT Sans',
										'Vollkorn'		=>'Vollkorn',
										'Ubuntu'		=>'Ubuntu',
										'Neucha'		=>'Neucha',
										'Cuprum'		=>'Cuprum'
							);
							?>
                            <select onchange="javascript: onCPApply();" name="ytcpanel_googleWebFont" class="cp_select">
							<?php foreach($googleFont as $k=>$v):?>
                                <option value="<?php echo $v; ?>"<?php echo ($var_yttheme->getParam('googleWebFont')==$v)?' selected="selected"':'';?>><?php echo $k; ?></option>
                            <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <!-- Body font-size -->
                    <div class="cp-item">
                        <span>Body font-size</span>
                        <div class="inner">
                            <?php 
							$fontfamily = array(
										 '10px'=>'10px',
										 '11px'=>'11px',
										 '12px'=>'12px',
										 '13px'=>'13px',
										 '14px'=>'14px',
										 '15px'=>'15px',
										 '16px'=>'16px',
										 '17px'=>'17px',
										 '18px'=>'18px'
							);
							?>
                            <select onchange="javascript: onCPApply();" name="ytcpanel_fontsize" class="cp_select">
							<?php foreach($fontfamily as $k=>$v):?>
                                <option value="<?php echo $v; ?>"<?php echo ($var_yttheme->getParam('fontsize')==$v)?' selected="selected"':'';?>><?php echo $k; ?></option>
                            <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <!-- Body font-family -->
                    <div class="cp-item body-fontfamily">
                        <span>Body font-family</span>
                        <div class="inner">
                        <?php 
						$fontfamily = array(
									 'Arial'=>'arial',
									 'Arial Black'=>'arial-black',
									 'Courier New'=>'courier',
									 'Georgia'=>'georgia',
									 'Impact'=>'impact',
									 'Lucida Console'=>'lucida-console',
									 'Lucida Grande'=>'lucida-grande',
									 'Palatino'=>'palatino',
									 'Tahoma'=>'tahoma',
									 'Times New Roman'=>'times',
									 'Trebuchet'=>'trebuchet',
									 'Verdana'=>'verdana'
						);
						?>
                            <select onchange="javascript: onCPApply();" name="ytcpanel_font_name" class="cp_select">
							<?php foreach($fontfamily as $k=>$v):?>
                                <option value="<?php echo $v; ?>"<?php echo ($var_yttheme->getParam('font_name')==$v)?' selected="selected"':'';?>><?php echo $k; ?></option>
                            <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    
                </div>
                
            </div>
        </div>
        
    </div>
    <!-- Action button -->
    <div class="action">
    	<!--<input id="yt_button_cpanel" class="btn btn-info" type="button" onclick="javascript: onCPApply();" value="Apply" class="button" />-->
    	<a  class="btn btn-info reset" href="#" onclick="javascript: onCPResetDefault(TMPL_COOKIE);">Reset</a>
    </div>
    <div id="cpanel_btn" class="normal">
        <i class="icon-hand-right"></i>
    </div>
</div>

	<script type="text/javascript">
	// <![CDATA[ 
    $jsmart(document).ready(function($){
        /* Begin: Enabling miniColors */
        //$('.color-picker').miniColors();
		$('.body-background-color .color-picker').miniColors({
			
			change: function(hex, rgb) {
				$('body').css('background-color', hex); 
				createCookie(TMPL_NAME+'_'+($(this).attr('name').match(/^ytcpanel_(.*)$/))[1], hex, 365);
			}
		});
		$('.link-color .color-picker').miniColors({
			change: function(hex, rgb) {
				$('body a').css('color', hex);
				createCookie(TMPL_NAME+'_'+($(this).attr('name').match(/^ytcpanel_(.*)$/))[1], hex, 365);
			}
		});
		$('.text-color .color-picker').miniColors({
			change: function(hex, rgb) {
				$('.yt-col .label').css('color', hex);
				$('.contacts-index-index  .subtitle').css('color', hex);
				$('.ytc_background_theme1 .price-label').css('color', hex);
				$('#yt_slideshow .block-description span').css('color', hex);
				$('#yt_tabitem_reviewform th').css('color', hex);
				$('.block-wishlist .price-label').css('color', hex);
				$('.product-essential .ratings .rating-links a').css('color', hex);
				$('.product-essential .price-label').css('color', hex);
				$('.products-list  .price-label').css('color', hex);
				$('.products-grid  .price-label').css('color', hex);
				$('#crosssell-products-list .add-to-links a').css('color', hex);
				$('.product-essential .add-to-links a').css('color', hex);
				$('.product-essential .stock-status').css('color', hex);
				$('.products-list .stock-status').css('color', hex);
				$('#yt_tab_products .yt-tab-content .box-tags').css('color', hex);
				$('.toolbar').css('color', hex);
				$('.price-title').css('color', hex);
				$('.compare-table, .compare-table .price-label').css('color', hex);
				$('#crosssell-products-list  .price-label').css('color', hex);			
				$('body').css('color', hex);
				createCookie(TMPL_NAME+'_'+($(this).attr('name').match(/^ytcpanel_(.*)$/))[1], hex, 365);
			}
		});
		$('.header-background-color .color-picker').miniColors({
			change: function(hex, rgb) {
				$('#bg_menu').css('background-color', hex);
				$('.forbgmenu').css('background-color', hex);
				createCookie(TMPL_NAME+'_'+($(this).attr('name').match(/^ytcpanel_(.*)$/))[1], hex, 365);
			}
		});
		$('.footer-background-color .color-picker').miniColors({
			change: function(hex, rgb) {
				/* $('#yt_spotlight2').css('background-color', hex); */
				/* $('#yt_footer').css('background-color', hex); */
				$('#bg_footer_bottom').css('background-color', hex);
				createCookie(TMPL_NAME+'_'+($(this).attr('name').match(/^ytcpanel_(.*)$/))[1], hex, 365);
			}
		});
		/* End: Enabling miniColors */
		/* Begin: Set click pattern */
		function patternClick(el, paramCookie, assign){
			$(el).click(function(){
				oldvalue = $(this).parent().find('.active').html();
				$(el).removeClass('active');
				$(this).addClass('active');
				value = $(this).html();
				if(assign.length > 0){
					for($i=0; $i < assign.length; $i++){
						$(assign[$i]).removeClass(oldvalue);
						$(assign[$i]).addClass(value);
					}
				}
				if(paramCookie){
					$('input[name$="ytcpanel_'+paramCookie+'"]').attr('value', value);
					createCookie(TMPL_NAME+'_'+paramCookie, value, 365);
					
				}
			});
	
		}
        patternClick('.header-background-image .pattern', 'header-bgimage', Array('#bg_menu','.forbgmenu'));
        patternClick('.body-background-image .pattern',   'body-bgimage',   Array('#bd', ''));
        patternClick('.footer-background-image .pattern', 'footer-bgimage', Array('#bg_footer_bottom', '' /* '#yt_copyright' */	));
        /* End: Set click pattern */
		function templateSetting(array){
			if(array['0']){
				$('.body-background-color input.miniColors').attr('value', array['0']);
				$('.body-background-color a.miniColors-trigger').css('background-color', array['0']);
				$('input.ytcpanel_bgcolor').attr('value', array['0']);
			}
			if(array['1']){
				$('.link-color input.miniColors').attr('value', array['1']);
				$('.link-color a.miniColors-trigger').css('background-color', array['1']);
				$('input.ytcpanel_linkcolor').attr('value', array['1']);
			}
			if(array['2']){
				$('.text-color input.miniColors').attr('value', array['2']);
				$('.text-color a.miniColors-trigger').css('background-color', array['2']);
				$('input.ytcpanel_textcolor').attr('value', array['2']);
			}
			if(array['3']){
				$('.header-background-color input.miniColors').attr('value', array['3']);
				$('.header-background-color a.miniColors-trigger').css('background-color', array['3']);
				$('input.ytcpanel_header-bgcolor').attr('value', array['3']);
			}
			if(array['4']){
				$('.header-background-image .pattern').removeClass('active');
				$('.header-background-image .pattern.'+array['4']).addClass('active');
				$('input[name$="ytcpanel_header-bgimage"]').attr('value', array['4']);
			}
			if(array['5']){
				$('.footer-background-color input.miniColors').attr('value', array['5']);
				$('.footer-background-color a.miniColors-trigger').css('background-color', array['5']);
				$('input.ytcpanel_footer-bgcolor').attr('value', array['5']);
			}
			if(array['6']){
				$('.footer-background-image .pattern').removeClass('active');
				$('.footer-background-image .pattern.'+array['6']).addClass('active');
				$('input[name$="ytcpanel_footer-bgimage"]').attr('value', array['6']);
			}
			if(array['7']){
				$('.body-background-image .pattern').removeClass('active');
				$('.body-background-image .pattern.'+array['7']).addClass('active');
				$('input[name$="ytcpanel_body-bgimage"]').attr('value', array['7']);
			}
		}
		var array 				= Array('bgcolor'	,	'linkcolor'	,'textcolor'	,'header-bgcolor'	,'header-bgimage'	,'footer-bgcolor'	,'footer-bgimage', 	'body-bgimage'	);
		var array_yellow 		= Array('#222'	 	,	'#EDAA00'	,'#686868'		,'#000'				,'hpattern'			,'#000'				,'fpattern',		'pattern1'		);
		var array_pink	 		= Array('#222'	 	,	'#EF5BDC'	,'#686868'		,'#000'				,'hpattern'			,'#000'				,'fpattern',		'pattern1'		);
		var array_green 		= Array('#222'	 	,	'#9BC02B'	,'#686868'		,'#000'				,'hpattern'			,'#000'				,'fpattern',		'pattern1'		);
		var array_purple	 	= Array('#222'	 	,	'#8E4AFF'	,'#686868'		,'#000'				,'hpattern'			,'#000'				,'fpattern',		'pattern1'		);
		var array_cyan		 	= Array('#222'	 	,	'#3FC7CC'	,'#686868'		,'#000'				,'hpattern'			,'#000'				,'fpattern',		'pattern1'		);
		
		$('.theme-color.yellow').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_yellow);
			onCPApply();
		});
		$('.theme-color.pink').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_pink);
			onCPApply();
		});
		$('.theme-color.green').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_green);
			onCPApply();
		});
		$('.theme-color.purple').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_purple);
			onCPApply();
		});
		$('.theme-color.cyan').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
			createCookie(TMPL_NAME+'_'+'sitestyle', $(this).html().toLowerCase(), 365);
			templateSetting(array_cyan);
			onCPApply();
		});
    });
	// ]]> 
    </script>
<?php
}
?>