<?php 
$catergoryArray =array(3,34,17,18,4,36,20,21,70,65,22,19,5,23,26,29);

$layer = Mage::getSingleton('catalog/layer');
$_category = $layer->getCurrentCategory();
$currentCategoryId= $_category->getId();
if(in_array($currentCategoryId,$catergoryArray)):
  $slide_status=$this->getResponsivebannersliderEnabled(); 
   switch($currentCategoryId){ 
   	 case '3':
    	 case '34':
    	 case '17':
   	 case '18':
     		 $responsiveCategory = "3_34_17_18";
      		 break; 
         case '4':
    	 case '36':
    	 case '20':
   	 case '21':
   	 case '70':
     		 $responsiveCategory = "4_36_20_21_70";
      		 break; 
         case '65':
    	 case '22':
    	 case '19':
   	      	 $responsiveCategory = "65_22_19";
      		 break; 
         case '5':
    	 case '23':
    	 case '26':
    	 case '29':
   	      	 $responsiveCategory = "5_23_26_29";
      		 break;   		 
    }
   
?>

<?php    $slide_speed=$this->getResponsivebannersliderSpeed();   ?>
<?php    $slide_type=$this->getResponsivebannerSlideType(); ?>
<?php    $slide_BannerLoop=$this->getResponsivebannerBannerLoop(); ?>
<?php    $slide_PauseOnhover=$this->getResponsivebannerPauseOnhover(); ?>


<?php
// Module Enable/Dsable Function.......................................
if($slide_status==1){ ?>



<?php
// Module type Function.......................................
if($slide_type=='1'){ ?>




<?php  $cssurl =  str_replace('index.php/','',$this->getUrl());?>
<link rel="stylesheet" type="text/css" href="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/css/generic-nav.css'; ?>" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('responsiveslider/css/grid12.css'); ?>" media="all">


<!-- BEGIN GOOGLE ANALYTICS CODEs -->
 
 
<div class="the-slideshow-wrapper nested-container clearer">

<div style="height: 428px;" class="the-slideshow gen-slider-arrows2 gen-slider-pager1 gen-slider-pager1-pos-bottom-right grid12-9  ">

<ul class="slides">
<?php 

$connection = Mage::getSingleton('core/resource')->getConnection('core_write');
$prefix = Mage::getConfig()->getTablePrefix();
$tblname=$prefix.'mksresponsivebannerslider';
$sql = $connection->query("select * from $tblname where status='1' and category ='$responsiveCategory'");
while($row1 = $sql->fetch())
{
$title = $row1["title"];
$description = $row1["description"]; 
$urlx = $row1["image"]; 
$media_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$imgurl=$media_url.$urlx;
$url = $row1["url"]; 

?>
<li style="width: 100%; float: left; margin-right: -100%; position: relative; display: none;" class="slide">
<?php if(!empty($url)):
$url = $this->getUrl($url);
 ?>
<a href="<?php echo $url; ?>">
<?php endif;?>
<img src="<?php echo $imgurl; ?>" alt="<?php echo $title; ?>" title="<?php echo $title; ?>">
<div class="caption dark3" style="display:none">
<h2><?php echo $description; ?></h2>
</div>
<div class="caption dark1 top-right">
<h2></h2>
</div>
<?php if(!empty($url)): ?>
</a>
<?php endif;?>
</li>

<?php } ?>
</ul>
 
</div>
</div>

<!-- BEGIN GOOGLE ANALYTICS CODEs -->

<script type="text/javascript">
//<![CDATA[
//jQuery(function($) {
responsivemks = jQuery.noConflict(); 
responsivemks(window).load(function(){
responsivemks('.the-slideshow').flexslider({
namespace:"",
animation:'fade',
easing:'easeInOutCirc',
useCSS:	false,
animationLoop:<?php echo $slide_BannerLoop; ?>,
smoothHeight: true,
slideshowSpeed:<?php echo $slide_speed; ?>,
animationSpeed:	600,
pauseOnHover:<?php echo $slide_PauseOnhover; ?>
});
});
//]]>
</script>    

<?php 
// Module type 2 Function.......................................End
} ?>



<?php
// Module type 1 Function.......................................Start
if($slide_type=='2'){ ?>




<?php $cssurl =  str_replace('index.php/','',$this->getUrl());?>
<link rel="stylesheet" type="text/css" href="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/css/generic-nav.css'; ?>" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo $cssurl.'skin/frontend/base/default/responsiveslider/css/grid12.css'; ?>" media="all">




	


<div class="the-slideshow gen-slider-arrows2 gen-slider-pager1 gen-slider-pager1-pos-bottom-right grid12-9  ">
<ul class="slides" style="padding:0px!important;">
<?php 
$connection = Mage::getSingleton('core/resource')->getConnection('core_write');
$prefix = Mage::getConfig()->getTablePrefix();
$tblname=$prefix.'mksresponsivebannerslider';
$sql = $connection->query("select * from $tblname where status='1' and category ='$responsiveCategory'");
while($row1 = $sql->fetch())
{
$title = $row1["title"];
$description = $row1["description"]; 
$urlx = $row1["image"]; 
$media_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$imgurl=$media_url.$urlx;
$url = $row1["url"]; 
$url = $this->getUrl($url);
?>
<li class="slide">
<a href="<?php echo $url; ?>">
<img src="<?php echo $imgurl; ?>" alt="<?php echo $title; ?>" title="<?php echo $title; ?>">
<div class="caption dark3" style="display:none">
<h2><?php echo $description; ?></h2>
</div>
<div class="caption dark1 top-right">
<h2></h2>
</div>
</a></li>

 



<?php } ?>
</ul>
</div>
    
<script type="text/javascript">
//<![CDATA[
//jQuery(function($) {
responsivemks = jQuery.noConflict(); 
responsivemks(window).load(function(){
responsivemks('.the-slideshow').flexslider({
namespace:"",
animation:'slide',
easing:'easeInOutCirc',
useCSS:	false,
animationLoop:<?php echo $slide_BannerLoop; ?>,
smoothHeight: true,
slideshowSpeed:<?php echo $slide_speed; ?>,
animationSpeed:	600,
pauseOnHover:<?php echo $slide_PauseOnhover; ?>
});
});
//]]>
</script>  
        



<?php
// Module type 1 Function.......................................End
 } ?>


 

<?php }  ?>

 <script type="text/javascript">
 jQuery(function($) {
 
 $div_title=jQuery(".col-main .page-title").clone();
jQuery(".col-main .page-title").remove();
$div_description=jQuery(".col-main .category-description").clone();
jQuery(".col-main .category-description").remove();
jQuery( ".the-slideshow" ).before($div_title);
jQuery( ".the-slideshow" ).before($div_description);

});
</script>
<?php
endif;
?>