<?php
    $_productCollection = $this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $imgWidth = $this->product_image_width;
    $imgHeight = $this->product_image_height;
    if ($imgWidth <= 0 || $imgHeight <= 0){
    	$this->product_image_disp = false;
    }
?>

<div class="category-products">
	<?php if ($this->title){ ?>
	<?php 
		//$arr_word =  $this->title ? explode(' ',$this->title) : "";
		//$join_word = array_shift($arr_word).' <span>'.implode(' ',$arr_word).'</span>';
	 ?>	
	<div class="block-title"><strong><?php //echo $join_word; ?><?php echo $this->title ?></strong></div>
	<?php } ?>
    <div class="yt-products-container">
    <?php 
	if(!$_productCollection->count()){ ?>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
     <?php 
	}else{
		$row = 0;
        $col= 0;
        $count = 1;
		$i=0; 
		$_collectionSize = $_productCollection->count();
		foreach($_productCollection as $_product){
			$now = date("Y-m-d");
			$newsFrom= substr($_product->getData('news_from_date'),0,10);
			$newsTo=  substr($_product->getData('news_to_date'),0,10);
			$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
			
            ?>
			<?php if ($i++==0){ ?>
				<div class="products-grid">
					<div class="row products">
					<?php } ?>
						<div class="span2d4" data-normal="span4" data-tablet="span4" data-stablet="span6">
							<div class="item <?php echo ( ($count == $_productCollection->count()) || ($count%$this->getNumColumns()==0) )?"last":""; ?>">
								<div class="item-inner <?php /*bgcolor2-hover */ ?>font2">
					
									<div class="item-box">
										<?php
										if ($now>=$newsFrom && $now<=$newsTo){
											echo "<span class='newproduct-grid'>new</span>";
											//echo $now.' -- '.$newsFrom.' -- '.$newsTo;
										}
										if ($specialprice){
											echo "<span class='saleoff-grid'>sale off</span>";
										}
										?>
										<div class="product-image">											
			                				<?php if($_product->getData('sale_item') == '1'): ?>
			                						<div class='sale-item'><img src="<?php echo $this->getSkinUrl('images/sale-i.png') ?>" alt=""/> </div>
			                				<?php endif; ?>
			                				<?php if($_product->getData('new_item') == '1'): ?>
			                						<div class='new-item'><img src="<?php echo $this->getSkinUrl('images/new-i.png') ?>" alt=""/></div>
			                				<?php endif; ?>                            
											<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-imgs"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(280,186); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
											<div class="popup-box">
												<p><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><img src="<?php echo $this->getSkinUrl('images/heart.png') ?>" alt="" /></a></p>                                
												<p><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></p>
												<?php /* <p>	<a href="<?php echo Mage::getBaseUrl(); ?>/review/product/list/id/<?php echo $_product->getId(); ?>/#review-form">Add Review</a> </p> */ ?>
												<p><a title="<?php echo $this->__('Add to Cart') ?>" href="<?php echo $this->getAddToCartUrl($_product) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Buy') ?></span></span></a></p>
											</div>							
										</div>
										<?php //echo $this->getPriceHtml($_product, true) ?>
									</div>
									<div class="item-box-footer">
										<h2 class="product-name">
											<a class="fontcolor" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
											<?php 

												echo $_helper->productAttribute($_product, $_product->getName(), 'name');

											?>
											</a>
										</h2>	
																	
										<?php echo $this->getPriceHtml($_product, true) ?>
<!--										<a class="readmore fontcolor" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"><?php echo $this->__('More Detail')  ?></a> -->
					                    <div class="desc std" style="color: #909090;margin:0!important">
					                        <?php $s_des = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'); ?>
										<?php echo substr($s_des ,0, 50).'...' ; ?>
					                    </div>
										<?php /*	
										<?php if($_product->isSaleable()): ?>
											<a title="<?php echo $this->__('Add to Cart') ?>" href="<?php echo $this->getAddToCartUrl($_product) ?>" class="btn-cart bgcolor fontcolor" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span class="icon-plus"><?php echo $this->__('Add to Cart') ?></span></span></a>
										<?php else: ?>
											<span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>
										<?php endif; ?>	
										*/ ?>								
									</div>
									<?php /*<span class="inner-border border-hover"></span>*/ ?>
								</div>
							</div>
						</div>
					<?php // if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
					<?php if ($i==$_collectionSize){ ?>
					</div>
				</div>	<?php /*	end div products-grid	*/ ?>
<?php
 			} 	?>
<?php
		}	?>
<?php 	
	} 	?>
	</div>
</div>

