<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $helper = $this->helper('wordpress/search') ?>
<?php if ($helper->isEnabled()): ?>
<div class="block block-blog block-blog-search">
	<?php if ($title = $this->getTitle()): ?>
		<div class="block-title" id="block-blog-search">
			<strong><span><?php echo $this->__($title) ?></span></strong>
		</div>
	<?php endif; ?>
	<div class="block-content">
		<form method="get" action="<?php echo $this->getFormActionUrl() ?>" id="blog-search-form">
			<div class="blog-search">
				<input type="text" class="input-text" value="<?php echo $helper->getEscapedSearchString() ?>" name="<?php echo $helper->getQueryVarName() ?>" id="blog-search" />
				<script type="text/javascript">
				//<![CDATA[
					var wpSearchForm = Class.create(Varien.searchForm, {
						initialize : function($super, form, field, emptyText, useSeoUrls) {
							this.useSeoUrls = useSeoUrls;
							return $super(form, field, emptyText);
						},
						submit : function($super, event) {
							if (this.useSeoUrls) {
								var o = this.form.readAttribute('action');
								var n = this.form.readAttribute('action') + encodeURIComponent(this.field.getValue().replace(' ', '-')) + '/';
				
								this.form.writeAttribute('action', n);
								this.field.writeAttribute('disabled', 'disabled');
								
								if (!$super(event)) {
									this.form.writeAttribute('action', o);
									this.field.writeAttribute('disabled', null);
									
									Event.stop(event);
									return false;
								}
								
								return true;
							}
					
							return $super(event);
						}
					});
				
					var searchForm = new wpSearchForm('blog-search-form', 'blog-search', '<?php echo $this->__($helper->getDefaultInputValue()) ?>', true);
				//]]>
				</script>
			</div>
		</form>
	</div>
</div>
	                    <script type="text/javascript" >   
                            jQuery('#block-blog-search').each(function(){
                                jQuery(this).addClass('active');
                                jQuery(this).toggle(function(){
                                    jQuery(this).removeClass('active').next().slideUp(200);
                                },function(){
                                    jQuery(this).addClass('active').next().slideDown(200);
                                })
                            });                                          
                    </script> 
<?php endif; ?>