<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($tags = $this->getTags()): ?>
	<?php $tagCount = count($tags) ?>
	<div class="block block-blog block-blog-tag-cloud block-tags">
		<?php if ($title = $this->getTitle()): ?>
			<div class="block-title" id="block-blog-tag-cloud">
				<strong><span><?php echo $this->__($title) ?></span></strong>
			</div>
		<?php endif; ?>
		<div class="block-content">
			<ul class="tags-list">
				<?php foreach ($tags as $tag): ?>
					<li<?php if (--$tagCount < 1): ?> class="last"<?php endif; ?>><a href="<?php echo $tag->getUrl() ?>" style="font-size:<?php echo $this->getFontSize($tag) ?>%;"><?php echo $this->htmlEscape($tag->getName()) ?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
	                    <script type="text/javascript" >   
                            jQuery('#block-blog-tag-cloud').each(function(){
                                jQuery(this).addClass('active');
                                jQuery(this).toggle(function(){
                                    jQuery(this).removeClass('active').next().slideUp(200);
                                },function(){
                                    jQuery(this).addClass('active').next().slideDown(200);
                                })
                            });                                          
                    </script> 
<?php endif; ?>