<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="block block-blog block-blog-text">
	<?php if ($title = $this->getTitle()): ?>
		<div class="block-title" id="block-blog-text">
			<strong><span><?php echo $this->__($title) ?></span></strong>
		</div>
	<?php endif; ?>
	<div class="block-content">
		<?php echo $this->getText() ?>
	</div>
</div>
	                    <script type="text/javascript" >   
                            jQuery('#block-blog-text').each(function(){
                                jQuery(this).addClass('active');
                                jQuery(this).toggle(function(){
                                    jQuery(this).removeClass('active').next().slideUp(200);
                                },function(){
                                    jQuery(this).addClass('active').next().slideDown(200);
                                })
                            });                                          
                    </script> 