<?php
$storeId = Mage::app()->getStore()->getStoreId();
$ajax_cart		 		= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_cart', $storeId); 
$image_product_hover 	= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/image_product_hover', $storeId);
$rating_wishlist_compare	 			= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/rating_wishlist_compare', $storeId); 
$quick_view	 			= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_quickview', $storeId);  
$thumb_width =  Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/standard_image_width', $storeId);
$thumb_height = Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/standard_image_height', $storeId);
$_productCollection=$this->getProductCollection();
$r = $this->getFrontendHash();
$_helper = $this->helper('catalog/output');
?>
<div class="slider-items-products">
<div class="home-list-title"><h3 class="title"><?php echo $this->getWidgetTitle();?></h3></div>
<div id="nova_slider_<?php echo $r;?>" class="product-flexslider">
	<div class="slider-items slider-width-col<?php echo $this->getShowItems()?>">	
		<?php $i=0; foreach ($_productCollection as $_product): ?>
                    <?php
                        $oType = false;
                        $product = Mage::getModel('catalog/product');
                        $product->load($_product->getId());
                        foreach ($product->getOptions() as $o) {
                            $optionType = $o->getType();
                            if ($optionType == 'file') {
                                $oType = true;
                            }
                        }
                    ?>		
		
   		<div class="item">
			<div class="nova-product-images"> 
				<?php include('labels.phtml')  ?> 
				<?php if($quick_view): ?>
				
				<?php endif;?>
	            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
	                          <?php 
	                if($image_product_hover) { ?>
	                <div class="front margin-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></div>
	                <?php
		                 $_gallery = Mage::getModel('catalog/product') -> load($_product -> getId()) -> getMediaGalleryImages();
		                 foreach ($_gallery as $_image ):
	                 ?>
	                 <div class="product-img-additional back margin-image">
	                 	<img src="<?php echo $this -> helper('catalog/image') -> init($_product, 'thumbnail', $_image -> getFile()) -> resize($thumb_width, $thumb_height);?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
	                 </div>
	                 <?php
							break;
							endforeach;
					?>
					<?php
						}else{
					?>
						<div class="margin-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
					 	</div>
					<?php	
						}
					?>			               
	            </a>
				<div class="descriptions-hidden">		
					<div class="quick-act">
						<?php if($ajax_cart):?> 	
						<div class="button-ajax-cart-id-<?php echo $_product->getId()?>">
						<?php if($_product->isSaleable()): ?>
						<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) || $oType == true ) : ?>
							<a class="add_to_cart_small<?php if($oType == true) echo ' option-file';?>" onclick="ajaxcart('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>');"><?php echo __('Add to Cart')?></a> 
						<?php else:?>		
							<a class="ajaxcart_colorbox add_to_cart_small" href="<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>"><?php echo __('Add to Cart')?></a> 
						<?php endif; ?> 
						</div>
						<?php else:?>
							<a rel="tooltip" class="add_to_cart_small" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>');"><?php echo __('Add to Cart')?></a> 
						<?php endif; ?>
                                    <?php else: ?>
                                        <p class="availability out-of-stock pull-left" title="<?php echo $this->__('Out of stock') ?>">
                                            <span class="out"><?php echo $this->__('Out of stock') ?></span>
                                        </p>
                                    <?php endif; ?>
					</div>	
					<?php if($rating_wishlist_compare || $quick_view):?>	
					<div class="quick-whl">	
					<?php if($rating_wishlist_compare):?>			
						<?php if ($this->helper('wishlist')->isAllow()) : ?>
							<a title="Wishlist" class="add_to_wishlist_small button-ajax-wishlist-id-<?php echo $_product->getId()?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-id="<?php echo $_product->getId()?>"><i class="icon-wishlist"></i></a> 
						<?php endif; ?> 
						<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
							<a title="Compare" class="add_to_compare_small button-ajax-compare-id-<?php echo $_product->getId()?>" href="<?php echo $_compareUrl ?>" data-id="<?php echo $_product->getId()?>"><i class="icon-compare"></i></a> 
						<?php endif; ?>
					<?php endif; ?> 
						<?php if($quick_view):?>
						<div class="quickview-box">
							<a class="quickview_small" href="<?php echo $this->getUrl('ajax/index/quickview',array('product_id'=>$_product->getId()));?>" data-id="<?php echo $_product->getId()?>"><i class="icon-search"></i></a> 
						</div> 
						<?php endif;?>
					</div>	
					<?php endif;?>			
				</div>
		    </div>
	        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
			<?php echo $this->getPriceHtml($_product, true) ?>
							<div class="rating-product-box">
				            	<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							</div>				
	    </div>
		<?php endforeach; ?>
	</div>
</div>
</div>
<script type="text/javascript">
//<![CDATA[
	jQuery(document).ready(function($) {
		jQuery("#nova_slider_<?php echo $r;?> .slider-items").owlCarousel({
			items : <?php echo $this->getShowItems()?>, //10 items above 1000px browser width
	    	itemsDesktop : [1000,<?php echo $this->getShowItemsDesktop()?>], //5 items between 1000px and 901px
	      	itemsDesktopSmall : [900,<?php echo $this->getShowItemsDesktopSmall()?>], // 3 items betweem 900px and 601px
	      	itemsTablet: [600,<?php echo $this->getShowItemsTablet()?>], //2 items between 600 and 0;
	      	itemsMobile : [320,<?php echo $this->getShowItemsMobile()?>],
	      	navigation : true,
	      	navigationText : ["<i class=\"icon-left-open\"></i>","<i class=\"icon-right-open\"></i>"],
	      	pagination : false
    	});
	}); 
//]]>
</script>






