<?php
/**
 * @category     Inchoo
 * @package     Inchoo Featured Products
 * @author        Domagoj Potkoc, Inchoo Team <web@inchoo.net>
 * @modified    Mladen Lotar <mladen.lotar@surgeworks.com>, Vedran Subotic <vedran.subotic@surgeworks.com>
 */
?>

<?php 
$enableFeatured = Mage::getStoreConfig('featuredproducts/general/enable_featuredproducts');
if($enableFeatured==1):
    $_productCollection=$this->getFeaturedProductCollection();
    $_helper = $this->helper('catalog/output');
 ?>
    <h3><?php echo $this->__($this->getBlockLabel()) ?></h3>
   
     
      

            <?php
            $i = 0;
            $row = 0;
            foreach ($_productCollection as $_product):
                ?>

                    <?php if ($i == 0): ?>
                        <?php $row++; ?>
                         <ul class="products-grid row">
                    
        <?php endif; ?>
                      <li class="item  sylogicspan">
                      <div class="syllogic-left">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                            <img class="product-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($image_size, $image_size) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                        </a>
                        </div>
                        <div class="product-description syllogic-right">
                            <p>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>)">
                            <?php echo $this->htmlEscape($_product->getName()) ?>
                                </a>
                            </p>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>

                            <?php if (Mage::getStoreConfig('featuredproducts/general/price_visible')): ?>

                                <?php echo $this->getPriceHtml($_product, true, '-new') ?>

                                <?php if ($_product->isSaleable()): ?>
                                    <button type="button" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php else: ?>
                                    <div class="out-of-stock"><?php echo $this->__('Out of stock') ?></div>
                                <?php endif; ?>

        <?php endif; ?>

                        </div>
                   </li> 

                    <?php $i++;
                    if ($i == $this->getItemsPerRow()):
                        ?>
                    <?php $i = 0; ?>
                    </ul>
        <?php endif; ?>
    <?php endforeach; ?>

        

    </ul>
<?php endif; ?>

