<?php if (!$methods = $this->getMethods()) : ?>
<p><?php echo $this->helper('checkout')->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else : ?>
<dl class="sp-methods">
<?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
    <dt>
    <?php if( sizeof($this->getMethods()) > 1 ): ?>
        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" <?php if($_code =="cashondelivery"): ?> style='display:none;' <?php endif; ?> />
    <?php else: ?>
        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
    <?php endif; ?>
        <label for="p_method_<?php echo $_code ?>" <?php if($_code =="cashondelivery"): ?> style='display:none;' <?php endif; ?>><?php echo $this->htmlEscape($_method->getTitle()) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?> </label>
    </dt>
    <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
    <dd>
        <?php echo $html; ?>
    </dd>
    <?php endif; ?>
<?php endforeach; ?>
</dl>
<script type="text/javascript">
//<![CDATA[
<?php echo $this->getChildChildHtml('scripts'); ?>
payment.init();
//]]>
</script>
<?php endif; ?>
<script type="text/javascript">
jQuery(document).ready(function(){
 jQuery("input[name='billing[city]']").blur(function(){
 
   var method = jQuery("input[name='billing[city]']").val();
 
   if( method.toLowerCase() =="mumbai"){
     
     jQuery("#p_method_cashondelivery").show();
     jQuery("label[for='p_method_cashondelivery']").show();
    
   }
   else{
     jQuery("#p_method_cashondelivery").hide();
     jQuery("label[for='p_method_cashondelivery']").hide();
     jQuery("#payment_form_cashondelivery").hide();
     jQuery("#p_method_cashondelivery").attr("checked", false);
   }
  });
});	 
</script>